volumes:
    shm:
        driver: local
        driver_opts:
            type: tmpfs
            device: tmpfs
            o: size=2g

services:
    sidecar:
        image: ubuntu:latest
        command: bash
        stdin_open: true
        tty: true
        volumes:
          - shm:/dev/shm/nosv

    first:
        build: .
        command: ./matmul 8192 8192 4096 64
        depends_on:
            - sidecar
        pid: "service:sidecar"
        volumes:
            - shm:/dev/shm/nosv

    second:
        build: .
        command: ./matmul 8192 8192 4096 64
        depends_on:
            - sidecar
        pid: "service:sidecar"
        volumes:
            - shm:/dev/shm/nosv

    third:
        build: .
        command: ./matmul 8192 8192 4096 64
        depends_on:
            - sidecar
        pid: "service:sidecar"
        volumes:
            - shm:/dev/shm/nosv

    fourth:
        build: .
        command: ./matmul 8192 8192 4096 64
        depends_on:
            - sidecar
        pid: "service:sidecar"
        volumes:
            - shm:/dev/shm/nosv